#!/bin/sh

REPOSITORY_ROOT="$(git rev-parse --show-toplevel)"

echo "Checking code formatting..."

if ! dotnet format "$REPOSITORY_ROOT/CoursePortalMiniApi.csproj" \
    --verify-no-changes \
    --verbosity minimal
then
    echo "Formatting errors found."
    echo "Run: dotnet format CoursePortalMiniApi.csproj"
    exit 1
fi

echo "Formatting check passed."
exit 0
