#!/bin/sh

REPOSITORY_ROOT="$(git rev-parse --show-toplevel)"

dotnet format "$REPOSITORY_ROOT/CoursePortalMiniApi.csproj" \
    --verify-no-changes \
    --verbosity minimal

if [ $? -ne 0 ]; then
    echo "Formatting errors found."
    echo "Run: dotnet format CoursePortalMiniApi.csproj"
    exit 1
fi

exit 0
