<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="frontend\src\constants\constants.ts" />
    <None Remove="frontend\src\constants\CourseLevel.ts" />
    <None Remove="frontend\src\service\CourseRequestDto.ts" />
    <None Remove="frontend\src\service\CourseResponseDto.ts" />
    <None Remove="frontend\src\service\courseService.ts" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\ci.yml" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="frontend\src\constants\constants.ts" />
    <TypeScriptCompile Include="frontend\src\constants\CourseLevel.ts" />
    <TypeScriptCompile Include="frontend\src\interfaces\CourseRequestDto.ts" />
    <TypeScriptCompile Include="frontend\src\interfaces\CourseResponseDto.ts" />
    <TypeScriptCompile Include="frontend\src\service\courseService.ts" />
  </ItemGroup>

</Project>
